# Generated by Django 4.2.24 on 2025-09-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
                ('segmento', models.CharField(choices=[('supermercado', 'Supermercado'), ('conveniencia', 'Conveniência'), ('padaria', 'Padaria'), ('restaurantes', 'Restaurantes'), ('outro', 'Outro')], max_length=100)),
            ],
        ),
    ]
