# Generated by Django 4.2.24 on 2025-09-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [    
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nome_estabelecimento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
