# Generated by Django 4.2.24 on 2025-09-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarios_nome_estabelecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='nome_usuario',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='segmento',
            field=models.CharField(choices=[('supermercado', 'Supermercado'), ('conveniencia', 'Conveniência'), ('padaria', 'Padaria'), ('restaurante', 'Restaurante'), ('outro', 'Outro')], max_length=100),
        ),
    ]
