# Generated by Django 4.2.24 on 2025-09-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('FRT', 'Frutas'), ('VRD', 'Verduras'), ('LTC', 'Laticínios'), ('CRN', 'Carnes'), ('GRS', 'Grãos'), ('OTS', 'Outros')], default='OTS', max_length=3)),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('quantidade_disponivel', models.PositiveIntegerField(default=0, verbose_name='Quantidade Disponível')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
