# Generated by Django 4.2.24 on 2025-09-13 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_usuarios_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria do produto', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto', max_length=200)),
                ('data_validade', models.DateField(help_text='Data de vencimento do produto')),
                ('quantidade_disponivel', models.PositiveIntegerField(help_text='Quantidade em estoque')),
                ('unidade_medida', models.CharField(blank=True, choices=[('quilograma', 'Quilograma (Kg)'), ('unidade', 'Unidade (1)'), ('litro', 'Litro (L)')], default='unidade', max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('normal', 'Normal'), ('atencao', 'Atenção'), ('urgente', 'Urgente'), ('vencido', 'Vencido'), ('vendido', 'Vendido')], max_length=20, null=True)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='core.categoria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['data_validade'],
            },
        ),
    ]
