# Generated by Django 4.2.24 on 2025-09-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
