# Generated by Django 4.2.24 on 2025-09-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuarios_email'),
        ('core', '0002_produto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
    ]
