# Generated by Django 4.2.24 on 2025-09-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('atencao', 'Atenção'), ('urgente', 'Urgente'), ('vencido', 'Vencido'), ('vendido', 'Vendido')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(blank=True, choices=[('quilograma', 'Quilograma'), ('unidade', 'Unidade'), ('litro', 'Litro')], default='unidade', max_length=20, null=True),
        ),
    ]
